name: Simulated Blue-Green CI/CD Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  cicd:
    name: 🔁 CI/CD Pipeline
    runs-on: ubuntu-latest

    env:
      COLOR: green
      BUILD_NUMBER: 1
      IMAGE: 1

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v4

      - name: 🧪 TC4 - Build & Lint
        run: |
          echo "Running bun install..."
          sleep 1
          echo "Running bun lint..."
          sleep 1
          echo "Running bunx next build..."
          sleep 2
          echo "Build artifact simulated."

      - name: 🐳 TC4 - Docker Build & Push
        run: |
          echo "Building Docker image: $IMAGE"
          sleep 2
          echo "Pushing image to Docker Hub..."
          sleep 1
          echo "Image pushed: $IMAGE"

      - name: ☸️ TC1/TC5 - Kubernetes Deployment
        run: |
          echo "Applying deployment-${COLOR}.yaml"
          sleep 2
          echo "Setting image: deployment/myapp-${COLOR} myapp=$IMAGE"
          echo "Waiting for rollout to complete..."
          sleep 2
          echo "Rollout successful for color: $COLOR"

      - name: ✅ TC1 - Check Blue & Green Deployments
        run: |
          echo "Pods in 'blue':"
          echo "myapp-blue-abc123 Running"
          echo "Pods in 'green':"
          echo "myapp-green-def456 Running"

      - name: 🔁 TC2 - Switch Service to ${{ env.COLOR }}
        run: |
          echo "Waiting for manual approval to switch service..."
          sleep 2
          echo "Patching service selector to color=${COLOR}"
          echo "Service now routes to ${COLOR} deployment"

      - name: 🧪 TC2 - Post-Switch Verification
        run: |
          echo "Validating service points to ${COLOR}"
          echo "Endpoints:"
          echo "10.1.1.5:3000, 10.1.1.6:3000"

      - name: 🔙 TC3 - Rollback
        if: always()  # Always show rollback simulation for demo
        run: |
          echo "Simulating rollback to previous version (blue)"
          sleep 1
          echo "Service now routing back to color=blue"
